
export const ADMIN_ALLLEAVES_REQUEST = 'ADMIN_ALLLEAVES_REQUEST'

export const ADMIN_ALLLEAVES_SUCCESS = 'ADMIN_ALLLEAVES_SUCCESS'

export const ADMIN_ALLLEAVES_FAIL = 'ADMIN_ALLLEAVES_FAIL'


export const ADMIN_EDITLEAVES_REQUEST = 'ADMIN_EDITLEAVES_REQUEST'

export const ADMIN_EDITLEAVES_SUCCESS = 'ADMIN_EDITLEAVES_SUCCESS'

export const ADMIN_EDITLEAVES_FAIL = 'ADMIN_EDITLEAVES_FAIL'


export const ADMIN_INDIVIDUALEDITLEAVES_REQUEST = 'ADMIN_INDIVIDUALEDITLEAVES_REQUEST'

export const ADMIN_INDIVIDUALEDITLEAVES_SUCCESS = 'ADMIN_INDIVIDUALEDITLEAVES_SUCCESS'

export const ADMIN_INDIVIDUALEDITLEAVES_FAIL = 'ADMIN_INDIVIDUALEDITLEAVES_FAIL'


export const ADMIN_PENDINGLEAVES_REQUEST = 'ADMIN_PENDINGLEAVES_REQUEST'

export const ADMIN_PENDINGLEAVES_SUCCESS = 'ADMIN_PENDINGLEAVES_SUCCESS'

export const ADMIN_PENDINGLEAVES_FAIL = 'ADMIN_PENDINGLEAVES_FAIL'


export const ADMIN_UPDATE_REQUEST = 'ADMIN_UPDATE_REQUEST'

export const ADMIN_UPDATE_SUCCESS = 'ADMIN_UPDATE_SUCCESS'

export const ADMIN_UPDATE_FAIL = 'ADMIN_UPDATE_FAIL'


export const  ADMIN_GETINDIVIDUALPROFILE_REQUEST ='ADMIN_GETINDIVIDUALPROFILE_REQUEST'

export const  ADMIN_GETINDIVIDUALPROFILE_SUCCESS =' ADMIN_GETINDIVIDUALPROFILE_SUCCESS'

export const  ADMIN_GETINDIVIDUALPROFILE_FAIL =' ADMIN_GETINDIVIDUALPROFILE_FAIL'


export const ADMIN_UPDATEPROFILE_REQUEST='ADMIN_UPDATEPROFILE_REQUEST'

export const ADMIN_UPDATEPROFILE_SUCCESS='ADMIN_UPDATEPROFILE_SUCESS'

export const ADMIN_UPDATEPROFILE_FAIL='ADMIN_UPDATEPROFILE_FAIL'
