
export const ADMIN_ALLLEAVES_REQUEST = 'ADMIN_ALLLEAVES_REQUEST'

export const ADMIN_ALLLEAVES_SUCCESS = 'ADMIN_ALLLEAVES_SUCCESS'

export const ADMIN_ALLLEAVES_FAIL = 'ADMIN_ALLLEAVES_FAIL'


export const ADMIN_PENDINGLEAVES_REQUEST = 'ADMIN_PENDINGLEAVES_REQUEST'

export const ADMIN_PENDINGLEAVES_SUCCESS = 'ADMIN_PENDINGLEAVES_SUCCESS'

export const ADMIN_PENDINGLEAVES_FAIL = 'ADMIN_PENDINGLEAVES_FAIL'



export const ADMIN_UPDATE_REQUEST = 'ADMIN_UPDATE_REQUEST'

export const ADMIN_UPDATE_SUCCESS = 'ADMIN_UPDATE_SUCCESS'

export const ADMIN_UPDATE_FAIL = 'ADMIN_UPDATE_FAIL'

