
export const BLOGS_LIST_REQUEST = 'BLOGS_LIST_REQUEST'
export const BLOGS_LIST_SUCCESS = 'BLOGS_LIST_SUCCESS'
export const BLOGS_LIST_FAIL = 'BLOGS_LIST_FAIL'

export const NEWS_LIST_REQUEST = 'NEWS_LIST_REQUEST'
export const NEWS_LIST_SUCCESS = 'NEWS_LIST_SUCCESS'
export const NEWS_LIST_FAIL = 'NEWS_LIST_FAIL'

