export const EMPLOYEE_LIST_REQUEST = 'EMPLOYEE_LIST_REQUEST'
export const EMPLOYEE_LIST_SUCCESS = 'EMPLOYEE_LIST_SUCCESS'
export const EMPLOYEE_LIST_FAIL = 'EMPLOYEE_LIST_FAIL'


export const EMPLOYEE_LEAVES_REQUEST = 'EMPLOYEE_LEAVES_REQUEST'
export const EMPLOYEE_LEAVES_SUCCESS = 'EMPLOYEE_LEAVES_SUCCESS'
export const EMPLOYEE_LEAVES_FAIL = 'EMPLOYEE_LEAVES_FAIL'

export const EMPLOYEE_REMAININGLEAVES_REQUEST = 'EMPLOYEE_REMAININGLEAVES_REQUEST'
export const EMPLOYEE_REMAININGLEAVES_SUCCESS = 'EMPLOYEE_REMAININGLEAVES_SUCCESS'
export const EMPLOYEE_REMAININGLEAVES_FAIL = 'EMPLOYEE_REMAININGLEAVES_FAIL'


export const EMPLOYEE_DAILYHOURS_REQUEST = 'EMPLOYEE_DAILYHOURS_REQUEST'
export const EMPLOYEE_DAILYHOURS_SUCCESS = 'EMPLOYEE_DAILYHOURS_SUCCESS'
export const EMPLOYEE_DAILYHOURS_FAIL = 'EMPLOYEE_DAILYHOURS_FAIL'

export const EMPLOYEE_LEAVEAPPLY_REQUEST = 'EMPLOYEE_LEAVEAPPLY_REQUEST'
export const EMPLOYEE_LEAVEAPPLY_SUCCESS = 'EMPLOYEE_LEAVEAPPLY_SUCCESS'
export const EMPLOYEE_LEAVEAPPLY_FAIL = 'EMPLOYEE_LEAVEAPPLY_FAIL'



export const EMPLOYEE_DELETELEAVE_REQUEST = 'EMPLOYEE_DELETELEAVE_REQUEST'
export const EMPLOYEE_DELETELEAVE_SUCCESS = 'EMPLOYEE_DELETELEAVE_SUCCESS'
export const EMPLOYEE_DELETELEAVE_FAIL = 'EMPLOYEE_DELETELEAVE_FAIL'